### ISSUE TITLE
Windows Security Trojan:Win32/Znyonm

### ISSUE THREAD

**Issue by ctan13** [Z1ni/XGP-save-extractor#133]
Windows 11 Security detects a trojan whenever I attempt to download the exe.

**Comment by wingedshadowwolf** [comment]
I've got the same thing happening on Windows 10. Using Brave and Chrome.

**Comment by ToonNoah** [comment]
same here.

**Comment by Z1ni** [comment]
Those detections are false positives due to how the script is packaged. You can probably ignore the exe from scanning from settings. Alternatively you can install Python and download the release zip and run the main.py script manually.

From the [README](https://github.com/Z1ni/XGP-save-extractor?tab=readme-ov-file#running):
>Some anti-virus/anti-malware software can flag the executable as malicious. The executable is produced with [PyInstaller](https://pyinstaller.org/) and contains the Python interpreter alongside with the same main.py script as in this repo.
