### ISSUE TITLE
Elden Ring

### ISSUE THREAD

**Issue by Arrquiga** [Z1ni/XGP-save-extractor#176]
Hey, so using a new exploit available for Xbox One/Series consoles, is finally possible to extract save files from the internal storage. I've been able to get the Elden Ring save files using a script from the community, and I was wondering if using the container files, it could be possible to convert them to play with the Steam version of the game. The files are as follow:

[u_2535457671131701_00000000-0000-0000-0000-000070C95F35.zip](https://github.com/user-attachments/files/16326867/u_2535457671131701_00000000-0000-0000-0000-000070C95F35.zip)

I tried to repack them in a similar format to the PC saves, using a tool from the community, but the saves just aren't natively compatible.
[ER0000.zip](https://github.com/user-attachments/files/16326869/ER0000.zip)

If you guys could help me in any way, I would be really grateful. Thanks anyway, hope I can get an answer!

**Comment by Z1ni** [comment]
Looking at the files it seems that the PC saves are packaged inside a "BND4" container, but the Xbox saves are individual files (e.g. "userdata0002"). It seems possible that the files can be packaged to a BND4 container using stuff from https://github.com/soulsmods/SoulsFormatsNEXT/tree/master/SoulsFormats/Binder.
The files also maybe need renaming (Xbox -> PC), as the files inside your ER0000.zip sl2-file are named like "USER_DATA002" instead of "userdata0002" (note also the extra 0).

Here's your Xbox save as separate files extracted from the Xbox container: [ER_____0000.zip](https://github.com/user-attachments/files/16334961/ER_____0000.zip)

**Comment by Arrquiga** [comment]
Yes, I had already managed to extract them and use the individual files (after renaming them) to repack using this tool:
https://github.com/ividyon/WitchyBND
But even after doing that and getting the .sl2 file, the saves weren't compatible, hence why I thought maybe they needed some kind of convertion, such as XGP-Save-Extractor. I even tried to compare it with a regular Steam save using a hex editor, but I lack the knowledge to find out what exactly isn't working

**Comment by Z1ni** [comment]
This save extractor tool doesn't really do any special conversions of the save files themselves, mostly it just arranges and renames files. At most it concatenates files for some special formats (e.g. Starfield saves).

Unfortunately, I can't really help with the issues if you managed to create a seemingly valid BND file without the tools complaining and the filenames being the same. Maybe you'll have better luck talking to people that understand the Elden Ring save file structure? WitchyBND developers, [SoulsMods](https://github.com/soulsmods) developers?

**Comment by Arrquiga** [comment]
You're probably right. Sorry to bother and thank you for your time and help!

**Comment by Z1ni** [comment]
No worries!
