### ISSUE TITLE
Unable to convert without the game installed

### ISSUE THREAD

**Issue by RedCapcha** [Z1ni/XGP-save-extractor#189]
I played Starfield on Game Pass and then deleted it and downloaded the Steam version. I have the Game Pass save folder, but I don't have the game installed. So the converter doesn't want to do anything, what should I do?
![image](https://github.com/user-attachments/assets/9f0d920d-9e4a-4dfb-aff7-47421614ff5f)

**Comment by Z1ni** [comment]
See here https://github.com/Z1ni/XGP-save-extractor/issues/173#issuecomment-2229252732.

Do you mean that you have the wgs folder of the game backed up elsewhere?

**Comment by RedCapcha** [comment]
> See here [#173 (comment)](https://github.com/Z1ni/XGP-save-extractor/issues/173#issuecomment-2229252732).
> 
> Do you mean that you have the wgs folder of the game backed up elsewhere?

That's right.

**Comment by RedCapcha** [comment]
> See here [#173 (comment)](https://github.com/Z1ni/XGP-save-extractor/issues/173#issuecomment-2229252732).
> 
> Do you mean that you have the wgs folder of the game backed up elsewhere?

Is there some way to just re-convert a particular save? Why hasn't anyone thought of this yet.....

**Comment by RedCapcha** [comment]
Can I ask you to convert this save for me? I have been suffering with this problem for 3 days now and if you can help me I will be very grateful.
https://mega.nz/file/2WhygJRT#B2A9BvH3yO5Rr5ZkOh8RqPMxPHp6gxCowoH0ZdUkIIA

**Comment by Z1ni** [comment]
It seems that your single save is not split into multiple files as I've seen before with Starfield. You might be able to rename the `7FDF8B09B768430CB23258FEC93D5123` file under the `DC828B289F3D46C187CA15DC7A024E2D` folder to e.g. `Save1.sfs` and place it under `%USERPROFILE%\Documents\My Games\Starfield\Saves\` (you might need to format the save file name a bit differently, check other save files under the Steam save folder).

Your zip also contains only one save file and not the complete wgs folder structure. Without the `containers.index` file I (and the script) don't know the real file names. Also usually there should be multiple save files (quick save, autosaves, etc.), so this save is just one of those without us knowing which one it is.

This tool currently requires the complete wgs folder structure to work. Otherwise you could have copied the backed up saves into `%LOCALAPPDATA%\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\` and ran the tool to extract the saves.

**Comment by RedCapcha** [comment]
> It seems that your single save is not split into multiple files as I've seen before with Starfield. You might be able to rename the `7FDF8B09B768430CB23258FEC93D5123` file under the `DC828B289F3D46C187CA15DC7A024E2D` folder to e.g. `Save1.sfs` and place it under `%USERPROFILE%\Documents\My Games\Starfield\Saves\` (you might need to format the save file name a bit differently, check other save files under the Steam save folder).
> 
> Your zip also contains only one save file and not the complete wgs folder structure. Without the `containers.index` file I (and the script) don't know the real file names. Also usually there should be multiple save files (quick save, autosaves, etc.), so this save is just one of those without us knowing which one it is.
> 
> This tool currently requires the complete wgs folder structure to work. Otherwise you could have copied the backed up saves into `%LOCALAPPDATA%\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\` and ran the tool to extract the saves.

I originally did it this way, but when renaming the file, the game gives a connection error with Bethesda servers. Apparently there is some kind of protection against this or I don't even know.

![image](https://github.com/user-attachments/assets/bd141477-09a2-487c-a4f5-e18299600cb0)

**Comment by Z1ni** [comment]
The error visible in the screenshot is caused by the missing `containers.index` in the folder also seen in the screenshot. Your wgs folder is incomplete, that's what the error means in this case. The Xbox app seems to leave the folder in that state after uninstalling a game.

If you don't have the other files and renaming the file correctly doesn't help (maybe create a new save in the Steam version and then replace the created file with the file from your backup with the same name?), I don't really have a 100%-sure-to-work solution for you. I don't know if the Steam version itself syncs the saves to Bethesda and that causes an error. Hard to say without seeing the error etc.

If you still have the Game Pass subscription you might be able to re-download the game and then have the complete save files to back up and try again with the complete save files.

**Comment by RedCapcha** [comment]
> The error visible in the screenshot is caused by the missing `containers.index` in the folder also seen in the screenshot. Your wgs folder is incomplete, that's what the error means in this case. The Xbox app seems to leave the folder in that state after uninstalling a game. Also there should be a user folder before that folder seen in the screenshot, so the folder structure is invalid as seen here.
> 
> If you don't have the other files and renaming the file correctly doesn't help (maybe create a new save in the Steam version and then replace the created file with the file from your backup with the same name?), I don't really have a 100%-sure-to-work solution for you. I don't know if the Steam version itself syncs the saves to Bethesda and that causes an error. Hard to say without seeing the error etc.
> 
> If you still have the Game Pass subscription you might be able to re-download the game and then have the complete save files to back up and try again with the complete save files.

It was a lot simpler than that. You just had to write a value in StarfieldCustom.ini. 
[Archive]
bInvalidateOlderFiles=1
sResourceDataDirsFinal=
And as you wrote below rename the save file and now everything worked like magic. In fact, the existence of the XGP project does not make much sense since all this can be done in a couple of clicks without third-party utilities. Thanks for the advice, my problem is solved.

**Comment by Z1ni** [comment]
Great that everything worked out!

>the existence of the XGP project does not make much sense since all this can be done in a couple of clicks without third-party utilities

At least at some point the Starfield save format was not exactly the same as the Steam save format, so this tool was helpful. I'm not sure about the current save file format. Also this tool supports other games which may or may not have differing file formats and/or filenames. But yes, the data's all there and all in all this is just a convenience tool.
