### ISSUE TITLE
Support for [Remnant: From the Ashes]

### ISSUE THREAD

**Issue by JadH97** [Z1ni/XGP-save-extractor#73]

**Comment by JadH97** [comment]
Hi,
Thanks for providing such awesome tool. If I may ask, how long it takes to get my game supported?

**Comment by Z1ni** [comment]
Hey, sorry for the delay!

I've added support for Remnant: From the Ashes, but as I don't have it, I can't confirm if it works correctly.
What I've seen from a random downloaded Steam save and your wgs, it _should_ work.

If you have Python installed, you can try to download the repo and run the main.py script, but if you don't have the know-how, you can wait a bit so that I can create an exe release later today.

**Comment by Z1ni** [comment]
This is now supported in the latest release https://github.com/Z1ni/XGP-save-extractor/releases
